export default screen = { 
    home: 'Scar',
    splash: 'Screen Splash',
    singup: 'Screen SingUp',
    servicesCatalog: 'Bitacora de servicios',
    sensorReading: 'Todos los sensores',
    settings: 'Screen Settings',
    profile: 'Perfil',
    login: 'Screen Login',
    fallas: 'FallasDTC',
    emissions: 'Pruebas de emisiones',
    cardata: 'Screen CarData',
    board: 'Screen Board',
    blueetooth: ' Elegir Dispositivo',
    binnacle: 'Bitacora de servicios',
    automative1: '5,000 km',
    automative2: '10,000 km',
    tabs: 'HomeTabs',
    
};