export default screen = { 
    home: 'Scar',
    splash: 'Screen Splash',
    singup: 'Screen SingUp',
    servicesCatalog: 'Bitacora de servicios',
    sensorReading: 'Screen SensorReading',
    settings: 'Screen Settings',
    profile: 'Perfil',
    login: 'Screen Login',
    fallas: 'FallasDTC',
    emissions: 'Screen EmissionsTest',
    cardata: 'Screen CarData',
    board: 'Screen Board',
    blueetooth: ' Elegir Dispositivo',
    binnacle: 'Bitacora de servicios',
    automative1: 'Screen AutomativeService1',
    automative2: 'Screen AutomativeService2',
    tabs: 'HomeTabs',
    
};